// auto-generated by gen_prov_test.py -- real firmware source, CommonCrypto AES.
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include <CommonCrypto/CommonCryptor.h>

static const uint8_t ZERO16[16] = {0};
static void aes_ecb_raw(const uint8_t key[16], const uint8_t in[16], uint8_t out[16]) {
    size_t moved = 0;
    CCCrypt(kCCEncrypt, kCCAlgorithmAES, kCCOptionECBMode, key, 16, NULL,
            in, 16, out, 16, &moved);
}
void mesh_cmac(const uint8_t key[16], const uint8_t *msg, size_t len, uint8_t out[16]);
void mesh_s1(const uint8_t *msg, size_t len, uint8_t out[16]);
void mesh_k1(const uint8_t *n, size_t nlen, const uint8_t salt[16],
             const uint8_t *p, size_t plen, uint8_t out[16]);

static void shift_left(const uint8_t in[16], uint8_t out[16]) {
    uint8_t carry = 0;
    for (int i = 15; i >= 0; i--) {
        out[i] = (uint8_t)((in[i] << 1) | carry);
        carry = (in[i] & 0x80) ? 1 : 0;
    }
}

void mesh_cmac(const uint8_t key[16], const uint8_t *msg, size_t len,
               uint8_t out[16]) {
    uint8_t L[16] = {0}, K1[16], K2[16], X[16] = {0}, blk[16];
    aes_ecb_raw(key, L, L);

    shift_left(L, K1);
    if (L[0] & 0x80) K1[15] ^= 0x87;
    shift_left(K1, K2);
    if (K1[0] & 0x80) K2[15] ^= 0x87;

    size_t n = (len + 15) / 16;
    bool complete = (n != 0) && (len % 16 == 0);
    if (n == 0) n = 1;

    for (size_t i = 0; i + 1 < n; i++) {
        for (int j = 0; j < 16; j++) blk[j] = X[j] ^ msg[i * 16 + j];
        aes_ecb_raw(key, blk, X);
    }

    uint8_t last[16] = {0};
    size_t rem = len - (n - 1) * 16;
    if (complete) {
        memcpy(last, msg + (n - 1) * 16, 16);
        for (int j = 0; j < 16; j++) last[j] ^= K1[j];
    } else {
        if (rem) memcpy(last, msg + (n - 1) * 16, rem);
        last[rem] = 0x80;
        for (int j = 0; j < 16; j++) last[j] ^= K2[j];
    }
    for (int j = 0; j < 16; j++) blk[j] = X[j] ^ last[j];
    aes_ecb_raw(key, blk, out);
}

void mesh_s1(const uint8_t *msg, size_t len, uint8_t out[16]) {
    mesh_cmac(ZERO16, msg, len, out);
}

void mesh_k1(const uint8_t *n, size_t nlen, const uint8_t salt[16],
             const uint8_t *p, size_t plen, uint8_t out[16]) {
    uint8_t t[16];
    mesh_cmac(salt, n, nlen, t);
    mesh_cmac(t, p, plen, out);
}

void mesh_k2(const uint8_t netkey[16], uint8_t *nid, uint8_t enc[16],
             uint8_t priv[16]) {
    uint8_t salt[16], t[16], t1[16], buf[64];
    mesh_s1((const uint8_t *)"smk2", 4, salt);
    mesh_cmac(salt, netkey, 16, t);

    buf[0] = 0x00;
    buf[1] = 0x01;
    mesh_cmac(t, buf, 2, t1);                 // T1 = CMAC(T, P || 0x01), P = 0x00

    memcpy(buf, t1, 16);
    buf[16] = 0x00;
    buf[17] = 0x02;
    mesh_cmac(t, buf, 18, enc);               // T2

    memcpy(buf, enc, 16);
    buf[16] = 0x00;
    buf[17] = 0x03;
    mesh_cmac(t, buf, 18, priv);              // T3

    *nid = t1[15] & 0x7F;
}

void mesh_k3(const uint8_t netkey[16], uint8_t out[8]) {
    uint8_t salt[16], t[16], full[16];
    mesh_s1((const uint8_t *)"smk3", 4, salt);
    mesh_cmac(salt, netkey, 16, t);
    const uint8_t p[] = {'i', 'd', '6', '4', 0x01};
    mesh_cmac(t, p, sizeof(p), full);
    memcpy(out, full + 8, 8);
}

uint8_t mesh_k4(const uint8_t appkey[16]) {
    uint8_t salt[16], t[16], full[16];
    mesh_s1((const uint8_t *)"smk4", 4, salt);
    mesh_cmac(salt, appkey, 16, t);
    const uint8_t p[] = {'i', 'd', '6', 0x01};
    mesh_cmac(t, p, sizeof(p), full);
    return full[15] & 0x3F;
}

void mesh_beacon_key(const uint8_t netkey[16], uint8_t out[16]) {
    uint8_t salt[16];
    mesh_s1((const uint8_t *)"nkbk", 4, salt);
    const uint8_t p[] = {'i', 'd', '1', '2', '8', 0x01};
    mesh_k1(netkey, 16, salt, p, sizeof(p), out);
}

bool mesh_beacon_verify(const uint8_t netkey[16], const uint8_t beacon[21]) {
    uint8_t bk[16], t[16];
    mesh_beacon_key(netkey, bk);
    mesh_cmac(bk, beacon, 13, t);       // flags || network id || iv index
    return memcmp(t, beacon + 13, 8) == 0;
}



// ---- the two primitives that are mbedtls's, stubbed so the chain can be seen ----
static const uint8_t FIXED_SECRET[32] = {
    0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31};
static uint8_t g_ccm_key[16], g_ccm_nonce[13], g_ccm_plain[25];
static bool g_ccm_called = false;

bool prov_ecdh_generate(uint8_t pub_xy[64]) {
    for (int i = 0; i < 64; i++) pub_xy[i] = (uint8_t)(i * 3 + 1);
    return true;
}
bool prov_ecdh_shared(const uint8_t peer_xy[64], uint8_t secret[32]) {
    (void)peer_xy; memcpy(secret, FIXED_SECRET, 32); return true;
}
bool prov_ccm_encrypt(const uint8_t key[16], const uint8_t nonce[13],
                      const uint8_t *in, size_t len, uint8_t *out) {
    memcpy(g_ccm_key, key, 16); memcpy(g_ccm_nonce, nonce, 13);
    if (len == 25) memcpy(g_ccm_plain, in, 25);
    g_ccm_called = true;
    memset(out, 0xAA, len + 8);
    return true;
}

#include "../src/provisioner.cpp"

// ---- expected values, from tools/mesh.py over the same fixed transcript ----
#define E_CONF_P     "382f3c90079b2f701a0b492836a4f659"
#define E_CONF_D     "4166cc5da5f8bbf1297804578607039d"
#define E_SESS_KEY   "b8b0e920a636c0a05170b91bd83f887a"
#define E_SESS_NONCE "70463d7bd211b6d34f952094a9"
#define E_DEVKEY     "b0b010bc7ad7208bad26168cfbf659e9"
#define E_PROV_DATA  "bb1ce23dad4ff4222a0198216b92578f000000000000070007"

static int fails = 0;
static void unhex(const char *h, uint8_t *out, size_t n) {
    for (size_t i = 0; i < n; i++) {
        char b[3] = {h[i*2], h[i*2+1], 0};
        out[i] = (uint8_t)strtol(b, NULL, 16);
    }
}
static void check(const char *name, const uint8_t *got, const char *want, size_t n) {
    uint8_t w[64]; unhex(want, w, n);
    bool ok = memcmp(got, w, n) == 0;
    printf("%-28s %s\n", name, ok ? "PASS" : "FAIL");
    if (!ok) {
        fails++;
        printf("   got  "); for (size_t i = 0; i < n; i++) printf("%02x", got[i]);
        printf("\n   want %s\n", want);
    }
}
static void expect(const char *name, bool ok) {
    printf("%-28s %s\n", name, ok ? "PASS" : "FAIL");
    if (!ok) fails++;
}

static const uint8_t NETKEY[16] = {0xbb,0x1c,0xe2,0x3d,0xad,0x4f,0xf4,0x22,
                                   0x2a,0x01,0x98,0x21,0x6b,0x92,0x57,0x8f};
static const uint8_t CAPS[11] = {0x01,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};

static void run(Provisioner &p, bool corrupt_device_confirm) {
    uint8_t oob[16];  for (int i = 0; i < 16; i++) oob[i] = (uint8_t)(i * 11 + 3);
    uint8_t pub_d[64]; for (int i = 0; i < 64; i++) pub_d[i] = (uint8_t)(i * 5 + 7);
    uint8_t rand_d[16]; for (int i = 0; i < 16; i++) rand_d[i] = (uint8_t)(i * 13 + 5);
    uint8_t conf_d[16]; unhex(E_CONF_D, conf_d, 16);
    if (corrupt_device_confirm) conf_d[0] ^= 0xff;

    uint8_t buf[Provisioner::MAX_PDU], in[80];
    p.useStaticOOB(oob);
    p.begin(NETKEY, 0, 0, 7, 0x0007);

    size_t n = p.next(buf);
    expect("invite is sent first", n == 2 && buf[0] == 0x00 && buf[1] == 0x00);

    in[0] = 0x01; memcpy(in + 1, CAPS, 11); p.feed(in, 12);
    n = p.next(buf);
    expect("start asks for static oob", n == 6 && buf[0] == 0x02 && buf[3] == 0x01);
    n = p.next(buf);
    expect("public key follows start", n == 65 && buf[0] == 0x03);

    in[0] = 0x03; memcpy(in + 1, pub_d, 64); p.feed(in, 65);
    n = p.next(buf);
    expect("confirmation is sent", n == 17 && buf[0] == 0x05);
    if (n == 17) check("our confirmation", buf + 1, E_CONF_P, 16);

    in[0] = 0x05; memcpy(in + 1, conf_d, 16); p.feed(in, 17);
    n = p.next(buf);
    expect("random is sent", n == 17 && buf[0] == 0x06);

    in[0] = 0x06; memcpy(in + 1, rand_d, 16); p.feed(in, 17);
}

int main(void) {
    printf("provisioner derivation, against tools/mesh.py\n\n");
    Provisioner good;
    run(good, false);
    uint8_t buf[Provisioner::MAX_PDU];
    size_t n = good.next(buf);
    expect("provisioning data is sent", n == 34 && buf[0] == 0x07);
    expect("ccm was asked to encrypt", g_ccm_called);
    check("session key", g_ccm_key, E_SESS_KEY, 16);
    check("session nonce", g_ccm_nonce, E_SESS_NONCE, 13);
    check("provisioning data", g_ccm_plain, E_PROV_DATA, 25);
    check("device key", good.devkey(), E_DEVKEY, 16);
    expect("elements read from caps", good.elements() == 1);

    uint8_t complete[1] = {0x08};
    good.feed(complete, 1);
    expect("complete ends it", good.state() == Provisioner::DONE);

    printf("\na device that cannot prove it holds the code:\n");
    Provisioner bad;
    run(bad, true);
    expect("wrong confirmation is rejected", bad.state() == Provisioner::FAILED);
    expect("  ...as Confirmation Failed", bad.reason() == 0x05);
    expect("  ...and nothing more is sent", bad.next(buf) == 0);

    printf("\nthe attention timer, which is the codeless identity check:\n");
    Provisioner blink;
    uint8_t b[Provisioner::MAX_PDU];
    blink.useAttention(5);
    blink.begin(NETKEY, 0, 0, 7, 0x0007);
    size_t bn = blink.next(b);
    expect("invite carries the attention", bn == 2 && b[0] == 0x00 && b[1] == 5);

    // The trap this guards: begin() builds the Invite, so a setter called after
    // it is set for a PDU already queued -- and the handshake still completes,
    // just without the blink that was the entire reason for asking.
    Provisioner late;
    late.begin(NETKEY, 0, 0, 7, 0x0007);
    late.useAttention(5);
    bn = late.next(b);
    expect("...and is ignored if set late", bn == 2 && b[1] == 0x00);

    printf("\n%s\n", fails ? "FAILURES" : "all good");
    return fails ? 1 : 0;
}
