// Generated by tools/puck-keys.py from driver-layer/host/release-keys.d -- do not edit by hand.
//
// The maker's public keys, raw ed25519, 2 of them. They are here so that a puck flashed today can
// verify a signature later: a key cannot be added to a puck after its cable visit, so it goes in
// before anything needs it. Nothing reads this yet -- see docs/puck-updates.md, "The keys, whether
// or not anything checks them yet".
//
// Two, not one, for the reason docs/updates.md gives: losing the only key means no puck in any house
// can ever be updated again, and on a puck that is not recoverable with a keyboard.
#pragma once

#include <stdint.h>

#define N_RELEASE_KEYS 2

// `volatile` here is load-bearing, not decoration, and `used` on its own was not enough.
//
// Reading a byte or two of a plain const array lets the compiler fold those bytes into the caller
// and leave the array unreferenced; -fdata-sections and --gc-sections then drop it at link time, and
// the image ships carrying no keys at all. `used` keeps the symbol in the object file but does not
// survive the linker's collection. `volatile` forces every read to be a real load from the array, so
// the symbol is genuinely referenced and the whole object -- all 32 bytes of each -- is kept.
//
// Check it, do not assume it: search the built binary for the key bytes. That is how this was found.
static const volatile uint8_t __attribute__((used)) RELEASE_KEYS[N_RELEASE_KEYS][32] = {
    { 0xd1, 0x23, 0xbc, 0xa9, 0x7e, 0x97, 0x36, 0x73, 0x7e, 0xad, 0xbf, 0x4b, 0x5a, 0x7e, 0x05, 0xb4, 0x61, 0x84, 0xf3, 0xda, 0x37, 0x60, 0x47, 0x2a, 0x8f, 0x0e, 0x6f, 0x32, 0xfb, 0xd5, 0x02, 0x5f },   // release.pub
    { 0x06, 0x04, 0x85, 0xdf, 0x60, 0x21, 0x5a, 0x21, 0xb3, 0xfe, 0x54, 0x5b, 0xe3, 0x94, 0x10, 0x1e, 0xf3, 0xa7, 0x2c, 0xd6, 0x4a, 0x55, 0x30, 0x97, 0x27, 0x4c, 0xcd, 0x44, 0x47, 0x80, 0x09, 0x32 },   // spare.pub
};
