// SPDX-FileCopyrightText: 2026 Temitope Adeyeri
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The boot splash, as text: the theme file, the script Plymouth runs, and the two numbers the
// wall's own service needs to know about it. Pure functions of sequence.mjs, so the test can
// check what is committed without drawing anything; render.mjs draws the images and writes these.
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { SPACE, COLOR, NAME, HOUSE, TIME, BREATH } from './sequence.mjs'

export const THEME = 'elyir'
export const DIR = `/usr/share/plymouth/themes/${THEME}`
// The images are drawn for the wall's 10-inch screen, 1920x1200, which is the boards at 4/3.
export const TARGET = { width: 1920, height: 1200 }
export const K = TARGET.width / SPACE.width
export const NAME_FRAMES = Math.round(TIME.write * TIME.fps) + 1

// What the images were drawn from. A change to either file without a fresh render fails the test.
export function fingerprint() {
  const h = createHash('sha256')
  for (const f of ['sequence.mjs', 'render.mjs']) h.update(readFileSync(new URL(f, import.meta.url)))
  return h.digest('hex').slice(0, 16)
}

export const themeFile = () => `[Plymouth Theme]
Name=Elyir
Description=The name written by hand, and a light that becomes the product's own.
ModuleName=script

[script]
ImageDir=${DIR}
ScriptFile=${DIR}/${THEME}.script
`

// Sourced by startup/wall.sh: how long after the splash began the ending may start, and how long it takes.
export const timingSh = () => `# Generated by startup/render.mjs from startup/sequence.mjs.
READY_AFTER=${TIME.readyAfter}
ENDING=${TIME.ending}
`

const n = (v) => +(+v).toFixed(4)

export function script() {
  const [pr, pg, pb] = COLOR.panel.map((c) => n(c / 255))
  return `# Elyir's startup. Generated by startup/render.mjs from startup/sequence.mjs -- edit those, not this.
#
# Plymouth calls refresh() fifty times a second. The name is written frame by frame, its i is
# dotted with a lamp that lights and breathes, the dot glides into the house, and the house waits
# breathing until the wall's service says the product is ready (plymouth update --status=elyir:ready).
# Then it opens onto the panel's own background, and the service hands the screen to the browser.

src = ${n(K)};
fps = ${TIME.fps}; name_frames = ${NAME_FRAMES};
name_left = ${n(NAME.left)}; name_top = ${n(NAME.top)};
tittle_x = ${n(NAME.tittle[0])}; tittle_y = ${n(NAME.tittle[1])}; tittle_size = ${NAME.tittleSize};
house_left = ${n(HOUSE.left)}; house_top = ${n(HOUSE.top)}; house_size = ${HOUSE.size};
lamp_x = ${n(HOUSE.lamp[0])}; lamp_y = ${n(HOUSE.lamp[1])}; lamp_size = ${n(HOUSE.lampSize)};
dotted = ${TIME.dotted}; lit_at = ${TIME.lit}; hold = ${TIME.hold}; name_out = ${TIME.nameOut};
leave = ${TIME.leave}; house_in = ${TIME.houseIn}; land = ${TIME.land};
ending = ${TIME.ending}; ready_after = ${TIME.readyAfter}; slow_after = ${TIME.slowAfter};
breath_period = ${BREATH.period}; low = ${BREATH.low};
panel_r = ${pr}; panel_g = ${pg}; panel_b = ${pb};
pi = 3.14159265;

screen_w = Window.GetWidth();
screen_h = Window.GetHeight();
s = Math.Min(screen_w / ${SPACE.width}, screen_h / ${SPACE.height});
ox = (screen_w - ${SPACE.width} * s) / 2;
oy = (screen_h - ${SPACE.height} * s) / 2;
r = s / src;
house_cx = ox + (house_left + house_size / 2) * s;
house_cy = oy + (house_top + house_size / 2) * s;

Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

fun clamp01(v) { if (v < 0) { return 0; } if (v > 1) { return 1; } return v; }
fun ramp(t, a, b) { return clamp01((t - a) / (b - a)); }
fun ease(x) { return x * x * (3 - 2 * x); }
fun breath(t) { return 0.5 + 0.5 * Math.Sin(t / breath_period * 2 * pi - pi / 2); }
fun pad(i) { if (i < 10) { return "0" + i; } return "" + i; }
fun fit(image) { if (r == 1) { return image; } return image.Scale(Math.Int(image.GetWidth() * r + 0.5), Math.Int(image.GetHeight() * r + 0.5)); }

# A sprite drawn from an image at a given width, centered on a point. Scaling is the expensive
# part, so it happens only when the width changes by a whole pixel; the width last used is
# kept in widths[] under the sprite's key.
fun place(key, sprite, image, cx, cy, w) {
  w = Math.Int(w + 0.5);
  if (w < 1) { w = 1; }
  if (global.widths[key] != w) {
    global.scaled[key] = image.Scale(w, Math.Int(w * image.GetHeight() / image.GetWidth() + 0.5));
    sprite.SetImage(global.scaled[key]);
    global.widths[key] = w;
  }
  sprite.SetX(cx - w / 2);
  sprite.SetY(cy - global.scaled[key].GetHeight() / 2);
}

dot_image = Image("dot.png");
unlit_image = Image("dot-unlit.png");
dot_glow_image = Image("dot-glow.png");
house_image = Image("house.png");
house_glow_image = Image("house-glow.png");

house_glow = Sprite(); house_glow.SetZ(4); house_glow.SetOpacity(0);
house = Sprite(); house.SetZ(5); house.SetOpacity(0);
name = Sprite(); name.SetZ(10); name.SetPosition(ox + name_left * s, oy + name_top * s, 10);
dot_glow = Sprite(); dot_glow.SetZ(20); dot_glow.SetOpacity(0);
unlit = Sprite(); unlit.SetZ(21); unlit.SetOpacity(0);
dot = Sprite(); dot.SetZ(22); dot.SetOpacity(0);
slow_image = fit(Image("slow.png"));
slow = Sprite(slow_image); slow.SetZ(30); slow.SetOpacity(0);
slow.SetPosition(Math.Int((screen_w - slow_image.GetWidth()) / 2), Math.Int(oy + 640 * s), 30);

global.frame = 0;
global.name_shown = -1;
global.ready_at = -1;
global.ending_at = -1;
global.widths["none"] = 0;

fun status(text) {
  if (text == "elyir:ready" && global.ready_at < 0) { global.ready_at = global.frame / 50; }
}

fun refresh() {
  global.frame = global.frame + 1;
  t = global.frame / 50;

  if (global.ready_at >= 0 && global.ending_at < 0 && t >= ready_after) { global.ending_at = t; }
  out = 0;
  if (global.ending_at >= 0) { out = ease(ramp(t, global.ending_at, global.ending_at + ending)); }
  Window.SetBackgroundTopColor(panel_r * out, panel_g * out, panel_b * out);
  Window.SetBackgroundBottomColor(panel_r * out, panel_g * out, panel_b * out);

  i = Math.Int(t * fps);
  if (i > name_frames - 1) { i = name_frames - 1; }
  if (i != global.name_shown && t < hold + name_out) {
    global.name_image = fit(Image("name-" + pad(i) + ".png"));
    name.SetImage(global.name_image);
    global.name_shown = i;
  }
  name.SetOpacity(1 - ease(ramp(t, hold, hold + name_out)));

  inn = ease(ramp(t, house_in - 0.2, house_in + 0.8));
  grow = (0.96 + 0.04 * inn) * (1 + 0.18 * out);
  house.SetOpacity(inn * (1 - out));
  if (inn > 0) { place("house", house, house_image, house_cx, house_cy, house_size * s * grow); }

  appear = ease(ramp(t, dotted, dotted + 0.3)) * (1 - out);
  k = ease(ramp(t, lit_at, lit_at + 0.8)) * (low + (1 - low) * breath(t));
  if (global.ending_at >= 0) { k = 1; }
  move = ease(ramp(t, leave, land));
  x = ox + (tittle_x + (lamp_x - tittle_x) * move) * s;
  y = oy + (tittle_y + (lamp_y - tittle_y) * move) * s;
  x = house_cx + (x - house_cx) * (1 + 0.18 * out);
  y = house_cy + (y - house_cy) * (1 + 0.18 * out);
  size = (tittle_size + (lamp_size - tittle_size) * move) * s * (1 + 0.18 * out);
  if (appear > 0) {
    place("unlit", unlit, unlit_image, x, y, size);
    place("dot", dot, dot_image, x, y, size);
    place("dot_glow", dot_glow, dot_glow_image, x, y, size * (32 + 180) / 32);
  }
  unlit.SetOpacity(appear);
  dot.SetOpacity(appear * k);

  # The dot's own small glow gives way to the house's wider one once it has landed.
  landed = ramp(t, land, land + 0.6);
  dot_glow.SetOpacity(appear * k * (1 - landed));
  house_glow.SetOpacity(k * landed * inn * (1 - out));
  if (landed > 0) { place("house_glow", house_glow, house_glow_image, x, y, house_size * 1.1 * s * (1 + 3 * out)); }

  gone = 1 - out;
  if (global.ready_at >= 0) { gone = 0; }
  slow.SetOpacity(ease(ramp(t, slow_after, slow_after + 1)) * gone);
}

Plymouth.SetUpdateStatusFunction(status);
Plymouth.SetRefreshFunction(refresh);
`
}
