#!/usr/bin/env python3
"""Emit esp32-bridge/include/secrets.h from the mesh key store.

The keys live outside the repo (~/.config/brilliant-mesh/mesh-net.json, or
$BRILLIANT_MESH_STORE). WiFi and MQTT settings are read from an existing
secrets.h if there is one, so regenerating after provisioning a new node does
not clobber them.

    python3 brilliant/tools/make_secrets.py > brilliant/esp32-bridge/include/secrets.h
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mesh  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
EXISTING = os.path.join(HERE, "..", "esp32-bridge", "include", "secrets.h")

DEFAULTS = {
    "WIFI_SSID": '"your-ssid"',
    "WIFI_PASS": '"your-password"',
    "MQTT_HOST": '"192.168.86.42"',
    "MQTT_PORT": "1883",
    "MQTT_USER": '""',
    "MQTT_PASS": '""',
    "MQTT_BASE": '"brilliant"',
}


def carry_over():
    """Keep WiFi/MQTT settings from an existing secrets.h."""
    vals = dict(DEFAULTS)
    if not os.path.exists(EXISTING):
        return vals
    text = open(EXISTING).read()
    for key in DEFAULTS:
        m = re.search(rf"^#define\s+{key}\s+(.+?)\s*(?://.*)?$", text, re.M)
        if m:
            vals[key] = m.group(1).strip()
    return vals


def carr(hexstr):
    return "{" + ", ".join(f"0x{b:02x}" for b in bytes.fromhex(hexstr)) + "}"


def main():
    net = mesh.load()
    if not net["nodes"]:
        sys.exit("no provisioned nodes in " + mesh.STORE)
    addr = sys.argv[1] if len(sys.argv) > 1 else sorted(net["nodes"])[0]
    node = net["nodes"][addr]
    v = carry_over()

    print(f"""// GENERATED by tools/make_secrets.py -- DO NOT COMMIT
// node {addr} ({node.get('name', '').strip()})
#pragma once

#define WIFI_SSID   {v['WIFI_SSID']}
#define WIFI_PASS   {v['WIFI_PASS']}

#define MQTT_HOST   {v['MQTT_HOST']}
#define MQTT_PORT   {v['MQTT_PORT']}
#define MQTT_USER   {v['MQTT_USER']}
#define MQTT_PASS   {v['MQTT_PASS']}
#define MQTT_BASE   {v['MQTT_BASE']}

static const uint8_t NET_KEY[16] = {carr(net['netkey'])};
static const uint8_t APP_KEY[16] = {carr(net['appkey'])};
static const uint8_t DEV_KEY[16] = {carr(node['devkey'])};

#define PROVISIONER_ADDR  0x{net['provisioner_addr']:04x}
#define NODE_ADDR         0x{node['unicast']:04x}
#define IV_INDEX          {net['iv_index']}""")


if __name__ == "__main__":
    main()
