#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Temitope Adeyeri
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Emit esp32-bridge/include/secrets.h from a mesh key store.

The keys live outside the repo ($BRILLIANT_MESH_STORE, default
~/.config/brilliant-mesh/mesh-net.json). For the always-on bridge point it at
the panel's keys:

    BRILLIANT_MESH_STORE=~/.config/brilliant-mesh/panel-net.json \\
        python3 brilliant/tools/make_secrets.py > /tmp/secrets.h && mv /tmp/secrets.h brilliant/esp32-bridge/include/secrets.h

A second puck on our own network gets its own header, carrying WiFi/MQTT over
from the first (then edit MQTT_BASE / SWITCH_* / DEVICE_LABEL by hand):

    python3 brilliant/tools/make_secrets.py --from brilliant/esp32-bridge/include/secrets.h > /tmp/s3.h \
        && mv /tmp/s3.h brilliant/esp32-bridge/include/secrets-s3.h

WiFi, MQTT and the bridge's tunables (BRIDGE_ADDR, PANEL_NODE, SWITCH_SEED,
SWITCH_EXCLUDE, POLL_MS, MOTION_*) are read back from an existing secrets.h,
so regenerating never clobbers what was set by hand. Edit those in the header
directly; the keys are the only thing this script owns.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mesh  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
EXISTING = os.path.join(HERE, "..", "esp32-bridge", "include", "secrets.h")

DEFAULTS = {
    "WIFI_SSID": '"your-ssid"',
    "WIFI_PASS": '"your-password"',
    "MQTT_HOST": '"192.168.86.42"',
    "MQTT_PORT": "1883",
    "MQTT_USER": '""',
    "MQTT_PASS": '""',
    "MQTT_BASE": '"mesh"',
    # bridge tunables; main.cpp has the same defaults and explains each
    "PANEL_NODE": '""',
    "SWITCH_SEED": "{0x000a, 0x0004, 0x0008, 0x000e}",
    "SWITCH_EXCLUDE": "{0x0012, 0x001a}",
    "POLL_MS": "250",
    "MOTION_ON_ABOVE": "4",
    "MOTION_HOLD_MS": "20000",
    "DEVICE_LABEL": '"Brilliant"',
}


def carry_over(existing):
    """Keep everything but the keys from an existing secrets header."""
    vals = dict(DEFAULTS)
    if not os.path.exists(existing):
        return vals
    text = open(existing).read()
    for key in DEFAULTS:
        m = re.search(rf"^#define\s+{key}\s+(.+?)\s*(?://.*)?$", text, re.M)
        if m:
            vals[key] = m.group(1).strip()
    return vals


def carr(hexstr):
    return "{" + ", ".join(f"0x{b:02x}" for b in bytes.fromhex(hexstr)) + "}"


def main():
    args = sys.argv[1:]
    existing = EXISTING
    if "--from" in args:                       # carry WiFi/MQTT/tunables over from another puck's header
        i = args.index("--from")
        existing = args[i + 1]
        del args[i:i + 2]
    net = mesh.load()
    v = carry_over(existing)
    panel = not net.get("nodes")
    if panel:
        who = f"panel network {mesh.k3(bytes.fromhex(net['netkey'])).hex()} (captured keys)"
    else:
        addr = args[0] if args else sorted(net["nodes"])[0]
        node = net["nodes"][addr]
        who = f"own network, node {addr} ({node.get('name', '').strip()})"

    print(f"""// GENERATED by tools/make_secrets.py -- DO NOT COMMIT
// {who}
#pragma once

#define WIFI_SSID   {v['WIFI_SSID']}
#define WIFI_PASS   {v['WIFI_PASS']}

#define MQTT_HOST   {v['MQTT_HOST']}
#define MQTT_PORT   {v['MQTT_PORT']}
#define MQTT_USER   {v['MQTT_USER']}
#define MQTT_PASS   {v['MQTT_PASS']}
#define MQTT_BASE   {v['MQTT_BASE']}

static const uint8_t NET_KEY[16] = {carr(net['netkey'])};
static const uint8_t APP_KEY[16] = {carr(net['appkey'])};
#define IV_INDEX          {net['iv_index']}

// The puck's mesh unicast is derived from its chip id (0x7000 | chip<<4); #define BRIDGE_ADDR 0x.... to pin it
// Pin the proxy to one switch's BLE address, or "" to take the strongest in range
#define PANEL_NODE        {v['PANEL_NODE']}
// Switches announced to Home Assistant at boot; anything else is learned from traffic
#define SWITCH_SEED       {v['SWITCH_SEED']}
// Addresses that answer but are not lights (the panel's controller element, the recorder)
#define SWITCH_EXCLUDE    {v['SWITCH_EXCLUDE']}
#define POLL_MS           {v['POLL_MS']}
#define MOTION_ON_ABOVE   {v['MOTION_ON_ABOVE']}
#define MOTION_HOLD_MS    {v['MOTION_HOLD_MS']}
#define DEVICE_LABEL      {v['DEVICE_LABEL']}""")

    if not panel:
        print(f"""
// Only meaningful on our own network (the bridge no longer sends devkey messages)
static const uint8_t DEV_KEY[16] = {carr(node['devkey'])};
#define PROVISIONER_ADDR  0x{net['provisioner_addr']:04x}
#define NODE_ADDR         0x{node['unicast']:04x}""")


if __name__ == "__main__":
    main()
