#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Temitope Adeyeri
# SPDX-License-Identifier: AGPL-3.0-or-later
"""index.html from canvas.json: every board at 1440x900, scaled to fit, with the annotation that argues it.
canvas.json is the source; run this after changing it, so the two cannot drift."""
import html, json, pathlib
here = pathlib.Path(__file__).parent
c = json.loads((here / "canvas.json").read_text())
notes = {a["id"]: a["text"] for a in c["annotations"]}
titles = {a["file"]: a["title"] for a in c["artboards"]}
# the reading order: a note, the boards it argues, in the order the canvas lays them out
order = c.get("reading", [])

def note(t):
    head, *rest = t.split("\n\n")
    return f'<section class="note"><h2>{html.escape(head)}</h2>{"".join(f"<p>{html.escape(p)}</p>" for p in rest)}</section>'

parts = []
for item in order:
    if item in notes: parts.append(note(notes[item]))
    else: parts.append(f'<figure><iframe src="{item}" width="1440" height="900" loading="lazy" scrolling="no"></iframe>'
                       f'<figcaption>{html.escape(titles[item])} &middot; <a href="{item}" target="_blank">open on its own</a></figcaption></figure>')

(here / "index.html").write_text(f"""<!doctype html>
<meta charset="utf-8">
<title>Setting up a bridge — the boards</title>
<!-- GENERATED by make-index.py from canvas.json; edit those, not this. -->
<style>
  :root {{ color-scheme: dark; }}
  body {{ margin: 0; background: #08090c; color: #f1eee8; font: 16px/1.55 "Instrument Sans", -apple-system, system-ui, sans-serif; }}
  header {{ padding: 56px 40px 8px; max-width: 78ch; }}
  h1 {{ font-size: 40px; font-weight: 400; letter-spacing: -.025em; margin: 0 0 12px; }}
  header p {{ color: #b9b5ad; margin: 0; }}
  main {{ display: flex; flex-direction: column; align-items: center; gap: 40px; padding: 40px 20px 120px; }}
  figure {{ margin: 0; width: min(1440px, 100%); }}
  iframe {{ border: 0; display: block; border-radius: 14px; transform-origin: 0 0; box-shadow: 0 30px 80px -30px rgba(0,0,0,.9); }}
  figcaption {{ margin-top: 14px; font-size: 13px; letter-spacing: .1em; text-transform: uppercase; color: #7f7d77; }}
  figcaption a {{ color: #e9b872; }}
  .note {{ width: min(880px, 100%); border-left: 2px solid rgba(233,184,114,.4); padding: 4px 0 4px 22px; }}
  .note h2 {{ font-size: 13px; letter-spacing: .12em; text-transform: uppercase; color: #e9b872; margin: 0 0 12px; font-weight: 500; }}
  .note p {{ margin: 0 0 12px; color: #b9b5ad; }}
</style>
<header>
  <h1>Setting up a bridge</h1>
  <p>The boards and the argument for each. Half one is getting the bridge into the house, drawn two ways; half two is
     getting a new switch onto the bridge &mdash; and, since a two-way is two switches and one light, saying so at setup.
     Every screen is 1440&times;900, the size of the wall.</p>
</header>
<main>{''.join(parts)}</main>
<script>
  function fit() {{
    for (const f of document.querySelectorAll('iframe')) {{
      const k = Math.min(1, f.parentElement.clientWidth / 1440)
      f.style.transform = 'scale(' + k + ')'; f.parentElement.style.height = (900 * k) + 'px'; f.parentElement.style.overflow = 'hidden'
    }}
  }}
  addEventListener('resize', fit); fit()
</script>
""")
print("index.html:", len(parts), "pieces")
