#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Temitope Adeyeri
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Regenerate test_cmac_native.c from the live text of src/mesh_crypto.cpp.

The firmware's AES-CMAC and key-derivation functions (k1..k4, the beacon key)
are lifted verbatim out of mesh_crypto.cpp and compiled on the Mac against
CommonCrypto's AES, so the code path that runs on the ESP32 is what gets
checked against the Mesh Profile 1.0.1 section 8 sample data. Run it after any
edit to those functions:

    python3 gen_native_test.py && clang -O1 -o /tmp/t test_cmac_native.c && /tmp/t
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src", "mesh_crypto.cpp")
OUT = os.path.join(HERE, "test_cmac_native.c")

text = open(SRC).read()
start = text.index("static void shift_left")
end = text.index("static void aes_ecb(")
body = text[start:end]

prelude = """// auto-generated by gen_native_test.py: real source text + CommonCrypto AES, run on the Mac
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include <CommonCrypto/CommonCryptor.h>

static const uint8_t ZERO16[16] = {0};

static void aes_ecb_raw(const uint8_t key[16], const uint8_t in[16], uint8_t out[16]) {
    size_t moved = 0;
    CCCrypt(kCCEncrypt, kCCAlgorithmAES, kCCOptionECBMode, key, 16, NULL,
            in, 16, out, 16, &moved);
}

void mesh_cmac(const uint8_t key[16], const uint8_t *msg, size_t len, uint8_t out[16]);
void mesh_s1(const uint8_t *msg, size_t len, uint8_t out[16]);
void mesh_k1(const uint8_t *n, size_t nlen, const uint8_t salt[16], const uint8_t *p, size_t plen, uint8_t out[16]);
void mesh_k2(const uint8_t netkey[16], uint8_t *nid, uint8_t enc[16], uint8_t priv[16]);
void mesh_k3(const uint8_t netkey[16], uint8_t out[8]);
uint8_t mesh_k4(const uint8_t appkey[16]);
void mesh_beacon_key(const uint8_t netkey[16], uint8_t out[16]);
bool mesh_beacon_verify(const uint8_t netkey[16], const uint8_t beacon[21]);

"""

tests = r"""
static void unhex(const char *h, uint8_t *out, size_t n) {
    for (size_t i = 0; i < n; i++) {
        char b[3] = {h[i * 2], h[i * 2 + 1], 0};
        out[i] = (uint8_t)strtol(b, NULL, 16);
    }
}
static int check(const char *name, const uint8_t *got, const char *want, size_t n) {
    uint8_t w[32];
    unhex(want, w, n);
    int ok = memcmp(got, w, n) == 0;
    printf("  %-8s %s\n", name, ok ? "PASS" : "FAIL");
    if (!ok) {
        printf("    got  ");
        for (size_t i = 0; i < n; i++) printf("%02x", got[i]);
        printf("\n    want %s\n", want);
    }
    return ok;
}

int main(void) {
    int ok = 1;
    uint8_t o[16], key[16], msg[64];

    // RFC 4493 AES-CMAC vectors
    unhex("2b7e151628aed2a6abf7158809cf4f3c", key, 16);
    mesh_cmac(key, msg, 0, o);
    ok &= check("cmac0", o, "bb1d6929e95937287fa37d129b756746", 16);
    unhex("6bc1bee22e409f96e93d7e117393172a", msg, 16);
    mesh_cmac(key, msg, 16, o);
    ok &= check("cmac16", o, "070a16b46b4d4144f79bdd9dd04a287c", 16);
    unhex("6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411", msg, 40);
    mesh_cmac(key, msg, 40, o);
    ok &= check("cmac40", o, "dfa66747de9ae63030ca32611497c827", 16);

    // Mesh Profile 1.0.1 section 8.1 / 8.4.3
    mesh_s1((const uint8_t *)"test", 4, o);
    ok &= check("s1", o, "b73cefbd641ef2ea598c2b6efb62f79c", 16);

    uint8_t n[16], nid, ek[16], pk[16], id[8], a[16], bk[16], beacon[21];
    unhex("f7a2a44f8e8a8029064f173ddc1e2b00", n, 16);
    mesh_k2(n, &nid, ek, pk);
    ok &= (nid == 0x7f);
    ok &= check("k2.enc", ek, "9f589181a0f50de73c8070c7a6d27f46", 16);
    ok &= check("k2.priv", pk, "4c715bd4a64b938f99b453351653124f", 16);
    mesh_k3(n, id);
    ok &= check("k3", id, "ff046958233db014", 8);
    unhex("3216d1509884b533248541792b877f98", a, 16);
    uint8_t aid = mesh_k4(a);
    printf("  %-8s %s (0x%02x)\n", "k4", aid == 0x38 ? "PASS" : "FAIL", aid);
    ok &= (aid == 0x38);

    unhex("7dd7364cd842ad18c17c2b820c84c3d6", n, 16);
    mesh_beacon_key(n, bk);
    ok &= check("beaconk", bk, "5423d967da639a99cb02231a83f7d254", 16);
    unhex("003ecaff672f673370123456788ea261582f364f6f", beacon, 21);
    int bv = mesh_beacon_verify(n, beacon);
    printf("  %-8s %s\n", "beacon", bv ? "PASS" : "FAIL");
    ok &= bv;
    beacon[13] ^= 1;
    bv = !mesh_beacon_verify(n, beacon);
    printf("  %-8s %s\n", "beacon!", bv ? "PASS" : "FAIL");
    ok &= bv;

    printf(ok ? "all pass\n" : "FAILURES\n");
    return ok ? 0 : 1;
}
"""

open(OUT, "w").write(prelude + body + tests)
print(f"wrote {OUT} ({len(body.splitlines())} lines lifted from mesh_crypto.cpp)")
