#!/usr/bin/env bash
# Put a recording into the repo's sounds folder in the shape the hub wants, and optionally onto a hub right now.
#
#   tools/add-sound.sh ~/Downloads/heavy-rain-loop.wav --name rain --from https://freesound.org/s/12345/ --license CC0 --by someone
#   tools/add-sound.sh ocean.mp3 --seconds 60 --hub hub.local
#
# The file becomes sounds/<name>.mp3: trimmed to --seconds (90 by default; the brain crossfades and repeats every
# sound out to ten minutes, so a short steady source is enough), stereo kept if present, 96 kbit/s. A line goes into
# sounds/CREDITS.md. With --hub, the same file is also copied into that hub's brain-data/sounds/ over ssh, so it
# shows up on the speaker tiles within a minute instead of at the next update. Needs ffmpeg.
set -euo pipefail
usage() { sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 1; }
[ $# -ge 1 ] || usage
IN="$1"; shift
NAME="" SECONDS_MAX=90 FROM="" LICENSE="" BY="" HUB="" HUB_DIR="/opt/home-hub"
while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --seconds) SECONDS_MAX="$2"; shift 2 ;;
    --from) FROM="$2"; shift 2 ;;
    --license) LICENSE="$2"; shift 2 ;;
    --by) BY="$2"; shift 2 ;;
    --hub) HUB="$2"; shift 2 ;;
    --hub-dir) HUB_DIR="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) echo "unknown option $1"; usage ;;
  esac
done
command -v ffmpeg >/dev/null || { echo "ffmpeg is needed (brew install ffmpeg / apt install ffmpeg)"; exit 1; }
[ -f "$IN" ] || { echo "no such file: $IN"; exit 1; }
HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$HERE/sounds"
# a name a person would read on a tile: rain, ocean-waves, box-fan
base="${NAME:-$(basename "${IN%.*}")}"
name="$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g')"
[ -n "$name" ] || { echo "could not make a name from $IN; pass --name"; exit 1; }
case "$name" in white|pink|brown) echo "$name is generated by the brain; pick another name"; exit 1 ;; esac
OUT="$OUT_DIR/$name.mp3"
mkdir -p "$OUT_DIR"
ffmpeg -y -v error -i "$IN" -t "$SECONDS_MAX" -vn -codec:a libmp3lame -b:a 96k -ar 44100 "$OUT"
dur="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$OUT" 2>/dev/null | cut -c1-5)"
size="$(du -h "$OUT" | cut -f1 | tr -d ' ')"
shown="$(printf '%s' "$name" | tr '-' ' ' | awk '{ print toupper(substr($0, 1, 1)) substr($0, 2) }')"   # rain-on-tent -> "Rain on tent", like the tile
echo "wrote sounds/$name.mp3  (${dur}s, $size) — shows on tiles as \"$shown\""
# the credit line
CREDITS="$OUT_DIR/CREDITS.md"
[ -f "$CREDITS" ] || printf '# Where each recording came from\n\n' > "$CREDITS"
if ! grep -q "^- \`$name.mp3\`" "$CREDITS"; then
  printf -- '- `%s.mp3` — %s — %s — %s\n' "$name" "${FROM:-source?}" "${LICENSE:-licence?}" "${BY:-author?}" >> "$CREDITS"
  [ -n "$FROM$LICENSE$BY" ] || echo "note: add the source, licence and author to sounds/CREDITS.md"
fi
# straight onto a hub, if asked
if [ -n "$HUB" ]; then
  echo "copying to $HUB:$HUB_DIR/driver-layer/brain-data/sounds/$name.mp3"
  ssh "$HUB" "sudo install -d -m 755 '$HUB_DIR/driver-layer/brain-data/sounds' && sudo tee '$HUB_DIR/driver-layer/brain-data/sounds/$name.mp3' >/dev/null" < "$OUT"
  echo "done; it is prepared and on the speaker tiles within a minute (open a room to prompt it)"
fi
