#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Temitope Adeyeri
# SPDX-License-Identifier: AGPL-3.0-or-later
"""The maker's public keys, as a header a puck -- or a strip -- can be built with.

    tools/puck-keys.py            regenerate both release_keys.h files below

A puck has no filesystem anybody can reach and no ssh, so a key that is not in its image at the
cable visit can never be in it: the verification code can ship whenever, the keys cannot. That is
why this runs now, while nothing checks a signature yet (docs/puck-updates.md).

The keys are the same ones the hub verifies its own releases with -- driver-layer/host/release-keys.d,
the directory docs/updates.md says is copied once at first install and never added to. One trust
anchor per house, not two. This reads them rather than restating them, so the header cannot drift
from the files a release is actually signed with.

An ed25519 public key in SPKI form is 44 bytes: a fixed 12-byte prefix and then the key. libsodium's
crypto_sign_verify_detached wants those last 32 bytes raw, so that is what comes out.
"""
import base64
import pathlib
import re
import sys

SPKI_PREFIX = bytes.fromhex("302a300506032b6570032100")
ROOT = pathlib.Path(__file__).resolve().parent.parent
KEYS = ROOT / "driver-layer/host/release-keys.d"
# Everything we flash that will one day check a signature, and the word for it in the header. A strip
# carries the same keys as a puck for the same reason (docs/strip.md, "Updates, the puck's way").
OUTS = [(ROOT / "brilliant/esp32-bridge/src/release_keys.h", "puck"),
        (ROOT / "strip/firmware/main/release_keys.h", "strip")]


def raw_key(path: pathlib.Path) -> bytes:
    body = re.sub(r"-----(BEGIN|END) PUBLIC KEY-----|\s", "", path.read_text())
    der = base64.b64decode(body)
    if len(der) != 44 or not der.startswith(SPKI_PREFIX):
        sys.exit(f"{path.name}: not an ed25519 public key in SPKI form ({len(der)} bytes)")
    return der[12:]


def main():
    pubs = sorted(KEYS.glob("*.pub"))
    if not pubs:
        sys.exit(f"no *.pub in {KEYS}")
    keys = [(p.stem, raw_key(p)) for p in pubs]

    rows = []
    for name, k in keys:
        octets = ", ".join(f"0x{b:02x}" for b in k)
        rows.append(f"    {{ {octets} }},   // {name}.pub")
    body = "\n".join(rows)

    for out, thing in OUTS:
        write(out, thing, keys, body)


def write(out: pathlib.Path, thing: str, keys: list, body: str) -> None:
    out.write_text(f"""// Generated by tools/puck-keys.py from driver-layer/host/release-keys.d -- do not edit by hand.
//
// The maker's public keys, raw ed25519, {len(keys)} of them. They are here so that a {thing} flashed today can
// verify a signature later: a key cannot be added to a {thing} after its cable visit, so it goes in
// before anything needs it. Nothing reads this yet -- see docs/puck-updates.md, "The keys, whether
// or not anything checks them yet".
//
// Two, not one, for the reason docs/updates.md gives: losing the only key means no {thing} in any house
// can ever be updated again, and on a {thing} that is not recoverable with a keyboard.
#pragma once

#include <stdint.h>

#define N_RELEASE_KEYS {len(keys)}

// `volatile` here is load-bearing, not decoration, and `used` on its own was not enough.
//
// Reading a byte or two of a plain const array lets the compiler fold those bytes into the caller
// and leave the array unreferenced; -fdata-sections and --gc-sections then drop it at link time, and
// the image ships carrying no keys at all. `used` keeps the symbol in the object file but does not
// survive the linker's collection. `volatile` forces every read to be a real load from the array, so
// the symbol is genuinely referenced and the whole object -- all 32 bytes of each -- is kept.
//
// Check it, do not assume it: search the built binary for the key bytes. That is how this was found.
static const volatile uint8_t __attribute__((used)) RELEASE_KEYS[N_RELEASE_KEYS][32] = {{
{body}
}};
""")
    print(f"{out.relative_to(ROOT)}: {len(keys)} keys ({', '.join(n for n, _ in keys)})")


if __name__ == "__main__":
    main()
